### ISSUE TITLE
Mod name changed if manually download from repository

### ISSUE THREAD

**Issue by Leaf5323** [NoviceCoder2000/UnCiv-Vanilla-Music-Pack#2]
Not sure whether this is a mod issue or game issue. 

- Current game version is `4.0.14`

- The mod manually downloaded is named `UnCiv Vanilla Music Pack main` rather than the original `UnCiv Vanilla Music Pack`

Because the mod is no longer able to be found in `game>Mods>Downloadable mods`, I tried to download it manually using `Download mod from URL` then found the issue. 

![Screenshot_20220517-104412_UnCiv](https://user-images.githubusercontent.com/74171766/168717818-3f457d29-2be2-4fb9-9b5e-4505c3459fcf.jpg)

**Comment by NoviceCoder2000** [comment]
Hmm... I'm not sure why there's a main popping out when downloaded manually either. But as for the direct download in unciv, I'll sort it out as soon as I have the chance.

**Comment by NoviceCoder2000** [comment]
There, I seem to have been able to fix the mod not appearing in the mod lists. If it worked in your end, kindly close this thread.

**Comment by Leaf5323** [comment]
I've tested it out and everything works perfectly!
Thanks for your work!🙂
