### ISSUE TITLE
Wrong Song

### ISSUE THREAD

**Issue by Caballero-Arepa** [NoviceCoder2000/UnCiv-Vanilla-Music-Pack#3]
I was playing and then the song of Songai of "Songai - Tribal War Shant - war" heard very *very* familiar, and indeed that is *not* an "tribal" war chant, that song is literaly from the "Republic Comando" game fron Star wars xD.

https://youtu.be/HhF7M1a5H5Y

If I were african I would be sad tbh xD

**Comment by NoviceCoder2000** [comment]
Well any suggestions then? I am out of idea for a war music for Songhai. :p

**Comment by NoviceCoder2000** [comment]
The new update uploaded should fix this issue.
